app = "xequtive-backend"

[build]
  builder = "paketobuildpacks/builder:base"

[http_service]
  internal_port = 5555
  force_https = true
  auto_stop_machines = true
  process_group = true

[env]
  PORT = "5555" 